import { createContext, useEffect, useMemo, useState } from 'react'

const LANGUAGE_STORAGE_KEY = 'language'

const COUNTRY_LANGUAGE_MAP = {
  '1': 'ko',
  '2': 'en',
  '3': 'en',
  '4': 'en',
  '5': 'en',
}

const translations = {
  ko: {
    navHome: '홈',
    navFeed: '피드',
    navDm: 'DM',
    navDark: '다크',
    navLight: '라이트',
    navLoading: '불러오는 중...',
    navProfileAlt: '프로필',
    navUserFallback: '사용자',
    navLogout: '로그아웃',
    navLogin: '로그인',
    navSignup: '회원가입',
    logoutConfirm: '로그아웃할까요?',
    logoutDone: '로그아웃되었습니다.',
    footerCopyright: '짤 2024 My Work. 모든 권리 보유.',
    footerPrivacy: '개인정보처리방침',
    footerTerms: '이용약관',
    footerContact: '문의하기',
    homeActivityHub: '활동 허브',
    homeOverviewUserSuffix: '님, 지금 필요한 정보를 한눈에 볼 수 있어요.',
    homeOverviewGuest: '중요한 정보를 한눈에 확인해보세요.',
    homeHeroDescription: '메시지, 저장한 글, 내 게시글, 트렌딩 태그를 한 곳에서 확인할 수 있어요.',
    homeOpenFeed: '피드 보기',
    homeCreatePost: '게시글 작성',
    homeLogIn: '로그인',
    homeUnreadDm: '안 읽은 DM',
    homeSavedPosts: '저장한 글',
    homeMyPosts: '내 게시글',
    homeTrendingTags: '트렌딩 태그',
    homeMessagesWaiting: '답장을 기다리는 메시지 수입니다.',
    homeShortlist: '북마크한 게시글 수입니다.',
    homePublishedPosts: '내가 작성한 게시글 수입니다.',
    homeTopicsMomentum: '지금 반응이 좋은 주제입니다.',
    homeNotifications: '알림',
    homeSyncing: '동기화 중...',
    homeLiveSummary: '실시간 요약',
    homeGuestTitle: '로그인하면 활동 보드가 열립니다',
    homeGuestDescription: '안 읽은 DM, 저장한 글, 최근 활동을 한 화면에서 확인할 수 있어요.',
    homeGoLogin: '로그인하러 가기',
    homeInboxCaughtUp: 'DM이 모두 확인된 상태예요',
    homeUnreadTitleSuffix: '개의 읽지 않은 메시지가 있어요',
    homeUnreadDescription: '최근 대화방으로 돌아가서 바로 이어서 답장할 수 있어요.',
    homeDmQuietDescription: '지금은 읽지 않은 DM이 없지만 대화 목록은 준비되어 있어요.',
    homeOpenDm: 'DM 열기',
    homeSavedReadySuffix: '개의 저장한 게시글을 다시 볼 수 있어요',
    homeSavedEmptyTitle: '관심 글을 저장해보세요',
    homeSavedDescription: '최근 북마크한 게시글이 아래에 표시됩니다.',
    homeSavedEmptyDescription: '피드의 저장 버튼으로 나만의 컬렉션을 만들 수 있어요.',
    homeBrowseFeed: '피드 둘러보기',
    homePostsPublishedSuffix: '개의 게시글이 작성되어 있어요',
    homeNoPostsYet: '아직 작성한 게시글이 없어요',
    homePostsDescription: '새 글을 올려 프로필을 계속 움직여보세요.',
    homeNoPostsDescription: '첫 게시글을 작성하고 활동을 시작해보세요.',
    homeRecentBookmarks: '최근 북마크',
    homeLoginRequired: '로그인 필요',
    homeSavedHint: '피드에서 저장한 글이 여기에 표시됩니다.',
    homeNoBookmarks: '아직 북마크한 글이 없어요. 피드에서 저장 버튼을 눌러보세요.',
    homeSavedFallback: '저장한 글',
    homeOpenPostDetails: '게시글 상세 보기',
    homeInboxSnapshot: '대화 요약',
    homeRecentRooms: '최근 대화방',
    homeInboxHint: '로그인하면 안 읽은 메시지와 최근 대화를 볼 수 있어요.',
    homeNoConversations: '아직 대화방이 없어요. 게시글이나 프로필에서 먼저 대화를 시작해보세요.',
    homeConversation: '대화방',
    homeOpenConversation: '대화 열기',
    homeTrendingHeading: '트렌딩 해시태그',
    homeTrendingHint: '지금 사람들이 많이 여는 주제',
    homeTrendingEmpty: '피드 데이터가 준비되면 트렌딩 태그가 표시됩니다.',
    profileMyProfile: '내 프로필',
    profileUpdated: '프로필이 수정되었습니다.',
    profileUpdateFailed: '프로필 수정에 실패했습니다.',
    profileUpdateError: '프로필 수정 중 오류가 발생했습니다.',
    profileEdit: '프로필 수정',
    profileLoading: '프로필을 불러오는 중...',
    profileStudio: '프로필 스튜디오',
    profileDescription: '프로필을 수정하고 커뮤니티 현황을 한 곳에서 살펴보세요.',
    profileFollowers: '팔로워',
    profileFollowing: '팔로잉',
    profileNickname: '닉네임',
    profileNicknamePlaceholder: '닉네임을 입력하세요',
    profileLastName: '성',
    profileFirstName: '이름',
    profilePhone: '전화번호',
    profileCountry: '국가',
    profileAddress1: '주소 1',
    profileAddress2: '주소 2',
    profileAddress1Placeholder: '기본 주소',
    profileAddress2Placeholder: '상세 주소',
    profileBirth: '생년월일',
    profileCancel: '취소',
    profileSave: '프로필 저장',
    profileSaving: '저장 중...',
    profileFollowUpdateLogin: '팔로우 상태를 바꾸려면 로그인이 필요합니다.',
    profileFollowLoadFailed: '팔로우 목록을 불러오지 못했습니다.',
    profileNoUsers: '표시할 사용자가 없습니다.',
    profileModalClose: '닫기',
    profileLoadingShort: '불러오는 중...',
    profileFollowSave: '저장 중...',
    postGoBack: '뒤로가기',
    postBackToFeed: '피드로 이동',
    postInvalidId: '올바르지 않은 게시글입니다.',
    postNotFound: '게시글을 찾을 수 없습니다.',
    postLoadFailed: '게시글을 불러오지 못했습니다.',
    postLoading: '게시글을 불러오는 중...',
    postDeleteConfirm: '이 게시글을 삭제할까요?',
    postDeleteDone: '게시글이 삭제되었습니다.',
    postDeleteFailed: '게시글 삭제에 실패했습니다.',
    postLoginLike: '좋아요를 누르려면 로그인이 필요합니다.',
    postLikeFailed: '좋아요 상태를 반영하지 못했습니다.',
    postLoginSave: '게시글을 저장하려면 로그인이 필요합니다.',
    postSaveFailed: '북마크 상태를 반영하지 못했습니다.',
    postLoginFollow: '팔로우하려면 로그인이 필요합니다.',
    postFollowFailed: '팔로우 상태를 반영하지 못했습니다.',
    postFollowListFailed: '팔로우 목록을 불러오지 못했습니다.',
    postMessage: '메시지',
    postDelete: '삭제',
    postSave: '저장',
    postSaved: '저장됨',
    postSaving: '저장 중...',
    postFollow: '팔로우',
    postFollowing: '팔로잉',
    postWorking: '처리 중...',
    postLike: '좋아요',
    postComments: '댓글',
    postViews: '조회',
    postThread: '댓글 스레드',
    postCommentsHeading: '댓글',
    postLoadedCountSuffix: '개 불러옴',
    postCommentPlaceholder: '댓글을 입력하세요...',
    postCommentLoginHint: '로그인 후 댓글을 작성할 수 있습니다.',
    postReplyDepthHint: '대댓글은 1단계까지 작성할 수 있습니다.',
    postCommentButton: '댓글 등록',
    postPosting: '등록 중...',
    postCommentsLoading: '댓글을 불러오는 중...',
    postNoComments: '아직 댓글이 없습니다. 첫 댓글을 남겨보세요.',
    postReplies: '답글',
    postLikes: '좋아요',
    postDeletedComment: '삭제된 댓글입니다.',
    postViewReplies: '답글 보기',
    postHideReplies: '답글 숨기기',
    postReply: '답글',
    postRepliesLoading: '답글을 불러오는 중...',
    postNoReplies: '아직 답글이 없습니다.',
    postReplyPlaceholder: '답글을 입력하세요...',
    postDeletedReply: '삭제된 답글입니다.',
    postLoginComment: '댓글을 쓰려면 로그인이 필요합니다.',
    postCommentFailed: '댓글 등록에 실패했습니다.',
    postLoginReply: '답글을 쓰려면 로그인이 필요합니다.',
    postReplyFailed: '답글 등록에 실패했습니다.',
    postLoadRepliesFailed: '답글을 불러오지 못했습니다.',
    postPublic: '전체 공개',
    postFollowersOnly: '팔로워 공개',
    postPrivate: '비공개',
    cardUnknown: '알 수 없음',
    cardJustNow: '방금 전',
    cardMinAgoSuffix: '분 전',
    cardHourAgoSuffix: '시간 전',
    cardDayAgoSuffix: '일 전',
    cardToggleLike: '좋아요 토글',
    cardLoginLike: '좋아요는 로그인 후 사용할 수 있습니다.',
    cardSave: '저장',
    cardSaved: '저장됨',
    cardMessage: '메시지',
    cardFollow: '팔로우',
    cardFollowing: '팔로잉',
    cardWorking: '처리 중...',
    cardSaving: '저장 중...',
    country1: '대한민국',
    country2: '미국',
    country3: '일본',
    country4: '중국',
    country5: '기타',
  },
  en: {
    navHome: 'Home',
    navFeed: 'Feed',
    navDm: 'DM',
    navDark: 'Dark',
    navLight: 'Light',
    navLoading: 'Loading...',
    navProfileAlt: 'Profile',
    navUserFallback: 'User',
    navLogout: 'Logout',
    navLogin: 'Login',
    navSignup: 'Sign up',
    logoutConfirm: 'Do you want to log out?',
    logoutDone: 'Logged out.',
    footerCopyright: 'ZZAL 2024 My Work. All rights reserved.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerContact: 'Contact',
    homeActivityHub: 'Activity Hub',
    homeOverviewUserSuffix: ', here is your live overview.',
    homeOverviewGuest: 'See what matters at a glance.',
    homeHeroDescription: 'Check messages, saved posts, your own posts, and trending tags in one place.',
    homeOpenFeed: 'Open feed',
    homeCreatePost: 'Create post',
    homeLogIn: 'Log in',
    homeUnreadDm: 'Unread DM',
    homeSavedPosts: 'Saved Posts',
    homeMyPosts: 'My Posts',
    homeTrendingTags: 'Trending Tags',
    homeMessagesWaiting: 'Messages waiting for your reply.',
    homeShortlist: 'Posts you bookmarked.',
    homePublishedPosts: 'Updates published from your account.',
    homeTopicsMomentum: 'Topics with momentum right now.',
    homeNotifications: 'Notifications',
    homeSyncing: 'Syncing...',
    homeLiveSummary: 'Live summary',
    homeGuestTitle: 'Log in to unlock your activity board',
    homeGuestDescription: 'Track unread DMs, saved posts, and recent conversations in one place.',
    homeGoLogin: 'Go to login',
    homeInboxCaughtUp: 'Your inbox is caught up',
    homeUnreadTitleSuffix: ' unread messages waiting',
    homeUnreadDescription: 'Jump back into recent conversations from the DM panel.',
    homeDmQuietDescription: 'No unread DM right now, but your chat list is ready.',
    homeOpenDm: 'Open DM',
    homeSavedReadySuffix: ' saved posts ready to revisit',
    homeSavedEmptyTitle: 'Start saving posts you want to revisit',
    homeSavedDescription: 'Your latest bookmarked posts are waiting below.',
    homeSavedEmptyDescription: 'Use the save button in the feed to build your own collection.',
    homeBrowseFeed: 'Browse feed',
    homePostsPublishedSuffix: ' posts published so far',
    homeNoPostsYet: 'You have not posted yet',
    homePostsDescription: 'Keep your profile moving with a fresh update today.',
    homeNoPostsDescription: 'Share your first update and start building momentum.',
    homeRecentBookmarks: 'Recent bookmarks',
    homeLoginRequired: 'Login required',
    homeSavedHint: 'Saved posts from the feed will appear here.',
    homeNoBookmarks: 'No bookmarks yet. Try the save button in the feed.',
    homeSavedFallback: 'Saved post',
    homeOpenPostDetails: 'Open post details',
    homeInboxSnapshot: 'Inbox Snapshot',
    homeRecentRooms: 'Recent rooms',
    homeInboxHint: 'Log in to see unread messages and active conversations.',
    homeNoConversations: 'No conversations yet. Start one from a post card or profile.',
    homeConversation: 'Conversation',
    homeOpenConversation: 'Open conversation',
    homeTrendingHeading: 'Trending Hashtags',
    homeTrendingHint: 'What people are opening now',
    homeTrendingEmpty: 'Trending topics will appear here once feed data is available.',
    profileMyProfile: 'My Profile',
    profileUpdated: 'Profile updated.',
    profileUpdateFailed: 'Failed to update profile.',
    profileUpdateError: 'An error occurred while updating your profile.',
    profileEdit: 'Edit Profile',
    profileLoading: 'Loading your profile...',
    profileStudio: 'Profile Studio',
    profileDescription: 'Update your profile and keep an eye on your community from one place.',
    profileFollowers: 'Followers',
    profileFollowing: 'Following',
    profileNickname: 'Nickname',
    profileNicknamePlaceholder: 'Enter your nickname',
    profileLastName: 'Last name',
    profileFirstName: 'First name',
    profilePhone: 'Phone',
    profileCountry: 'Country',
    profileAddress1: 'Address 1',
    profileAddress2: 'Address 2',
    profileAddress1Placeholder: 'Primary address',
    profileAddress2Placeholder: 'Apartment, suite, unit',
    profileBirth: 'Birth date',
    profileCancel: 'Cancel',
    profileSave: 'Save profile',
    profileSaving: 'Saving...',
    profileFollowUpdateLogin: 'Login is required to update follow status.',
    profileFollowLoadFailed: 'Failed to load follow list.',
    profileNoUsers: 'No users found.',
    profileModalClose: 'Close',
    profileLoadingShort: 'Loading...',
    profileFollowSave: 'Saving...',
    postGoBack: 'Go back',
    postBackToFeed: 'Back to feed',
    postInvalidId: 'Invalid post id.',
    postNotFound: 'Post not found.',
    postLoadFailed: 'Failed to load the post.',
    postLoading: 'Loading post...',
    postDeleteConfirm: 'Delete this post?',
    postDeleteDone: 'The post has been removed.',
    postDeleteFailed: 'Failed to delete the post.',
    postLoginLike: 'Log in to like posts.',
    postLikeFailed: 'Failed to update like state.',
    postLoginSave: 'Log in to save posts.',
    postSaveFailed: 'Failed to update bookmark.',
    postLoginFollow: 'Log in to follow users.',
    postFollowFailed: 'Failed to update follow state.',
    postFollowListFailed: 'Failed to load follow list.',
    postMessage: 'Message',
    postDelete: 'Delete',
    postSave: 'Save',
    postSaved: 'Saved',
    postSaving: 'Saving...',
    postFollow: 'Follow',
    postFollowing: 'Following',
    postWorking: 'Working...',
    postLike: 'Like',
    postComments: 'Comments',
    postViews: 'Views',
    postThread: 'Thread',
    postCommentsHeading: 'Comments',
    postLoadedCountSuffix: ' loaded',
    postCommentPlaceholder: 'Write a comment...',
    postCommentLoginHint: 'Log in to leave a comment.',
    postReplyDepthHint: 'Replies are available one level deep.',
    postCommentButton: 'Post comment',
    postPosting: 'Posting...',
    postCommentsLoading: 'Loading comments...',
    postNoComments: 'No comments yet. Start the conversation.',
    postReplies: 'Replies',
    postLikes: 'Likes',
    postDeletedComment: 'This comment has been deleted.',
    postViewReplies: 'View replies',
    postHideReplies: 'Hide replies',
    postReply: 'Reply',
    postRepliesLoading: 'Loading replies...',
    postNoReplies: 'No replies yet.',
    postReplyPlaceholder: 'Write a reply...',
    postDeletedReply: 'This reply has been deleted.',
    postLoginComment: 'Log in to comment.',
    postCommentFailed: 'Failed to create comment.',
    postLoginReply: 'Log in to write a reply.',
    postReplyFailed: 'Failed to create reply.',
    postLoadRepliesFailed: 'Failed to load replies.',
    postPublic: 'Public',
    postFollowersOnly: 'Followers',
    postPrivate: 'Private',
    cardUnknown: 'Unknown',
    cardJustNow: 'Just now',
    cardMinAgoSuffix: 'm ago',
    cardHourAgoSuffix: 'h ago',
    cardDayAgoSuffix: 'd ago',
    cardToggleLike: 'Toggle like',
    cardLoginLike: 'Login required to like',
    cardSave: 'Save',
    cardSaved: 'Saved',
    cardMessage: 'Message',
    cardFollow: 'Follow',
    cardFollowing: 'Following',
    cardWorking: 'Working...',
    cardSaving: 'Saving...',
    country1: 'Korea',
    country2: 'United States',
    country3: 'Japan',
    country4: 'China',
    country5: 'Other',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'ko')

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language)
    document.documentElement.lang = language
  }, [language])

  const setLanguageByCountry = (countryCode) => {
    setLanguage(COUNTRY_LANGUAGE_MAP[String(countryCode)] || 'en')
  }

  const value = useMemo(() => ({
    language,
    setLanguage,
    setLanguageByCountry,
    t: (key, fallback = '') => translations[language]?.[key] || fallback || key,
  }), [language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export default LanguageContext
